#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to
# another page
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/error-page.html
sudo sed -i '/location \/ {$/a error_page 404 /error-page.html;' /etc/nginx/sites-enabled/default
sudo service nginx restart
